# Generated by Django 6.1.1 on 2026-09-20 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe (USD / Global)'), ('RAZORPAY', 'Razorpay (INR / India)'), ('MANUAL', 'Admin Assigned')], default='STRIPE', max_length=20)),
                ('transaction_id', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('STRIPE', 'Stripe (USD / Global)'), ('RAZORPAY', 'Razorpay (INR / India)'), ('MANUAL', 'Admin Assigned')], default='STRIPE', max_length=20)),
                ('plan', models.CharField(choices=[('PRO_MONTHLY', 'Pro Trader Monthly'), ('PRO_YEARLY', 'Pro Trader Yearly'), ('ENTERPRISE', 'Enterprise / Institutional')], default='PRO_MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
