# Generated by Django 6.1.1 on 2026-09-20 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('preferred_market', models.CharField(choices=[('INDIA', 'India (NSE / BSE / MCX)'), ('USA', 'USA (NYSE / NASDAQ / COMEX)'), ('GLOBAL', 'Global All-Markets')], default='INDIA', max_length=10)),
                ('preferred_currency', models.CharField(choices=[('INR', 'INR (₹) - Indian Rupee'), ('USD', 'USD ($) - US Dollar')], default='INR', max_length=5)),
                ('preferred_gold_unit', models.CharField(choices=[('10g', '10 Grams (India MCX / Retail)'), ('oz', 'Troy Ounce (US COMEX / Global Spot)')], default='10g', max_length=5)),
                ('subscription_tier', models.CharField(choices=[('FREE', 'Free Explorer (3 Predictions/Day)'), ('PRO', 'Pro Trader (Unlimited + Signals)'), ('ENTERPRISE', 'Institutional / Enterprise API')], default='FREE', max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('credits_remaining', models.IntegerField(default=10)),
                ('predictions_used_today', models.IntegerField(default=0)),
                ('last_prediction_date', models.DateField(blank=True, null=True)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
