# Generated by Django 6.1.1 on 2026-09-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ticker (e.g. GC=F, GLD, GOLDBEES.NS, NVDA, RELIANCE.NS, ^NSEI)', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('COMMODITY', 'Commodity / Precious Metal'), ('EQUITY', 'Equity / Stock'), ('INDEX', 'Market Index'), ('FOREX', 'Forex Currency Pair')], default='COMMODITY', max_length=20)),
                ('market', models.CharField(choices=[('USA', 'United States (NYSE / NASDAQ / COMEX)'), ('INDIA', 'India (NSE / BSE / MCX)'), ('GLOBAL', 'Global 24/5 Market')], default='INDIA', max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('INR', 'INR (₹)')], default='INR', max_length=5)),
                ('display_unit', models.CharField(default='share', help_text='e.g. oz, 10g, share, points', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Pinned on dashboard header')),
                ('description', models.TextField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change_pct_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'market', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('USA', 'United States (NYSE / NASDAQ / COMEX)'), ('INDIA', 'India (NSE / BSE / MCX)'), ('GLOBAL', 'Global 24/5 Market')], default='GLOBAL', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Polarity: -1.0 (Strong Bearish) to +1.0 (Strong Bullish)')),
                ('sentiment_label', models.CharField(choices=[('BULLISH', 'Bullish / Positive'), ('BEARISH', 'Bearish / Negative'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('sentiment_confidence', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='market_data.asset')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('market', models.CharField(choices=[('USA', 'United States (NYSE / NASDAQ / COMEX)'), ('INDIA', 'India (NSE / BSE / MCX)'), ('GLOBAL', 'Global 24/5 Market')], default='GLOBAL', max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'code'],
                'unique_together': {('code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('timeframe', models.CharField(choices=[('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=5)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='market_data.asset')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['asset', 'timeframe', 'timestamp'], name='market_data_asset_i_455b5e_idx')],
                'unique_together': {('asset', 'timestamp', 'timeframe')},
            },
        ),
    ]
