# Generated by Django 6.1.1 on 2026-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialnews',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Polarity: -1.0 to +1.0'),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='timeframe',
            field=models.CharField(choices=[('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], default='1d', max_length=5),
        ),
    ]
