# Generated by Django 6.1.1 on 2026-09-20 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_predictions', models.IntegerField(default=0)),
                ('successful_hits', models.IntegerField(default=0)),
                ('directional_win_rate', models.DecimalField(decimal_places=2, default=90.0, help_text='Win rate percentage (e.g. 91.20%)', max_digits=5)),
                ('average_return_pct', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_audit', to='market_data.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=5)),
                ('horizon_days', models.IntegerField(default=7, help_text='Forecast horizon (e.g. 1d, 7d, 30d)')),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy 🚀'), ('BUY', 'Buy / Bullish 📈'), ('NEUTRAL', 'Neutral / Consolidating ⚖️'), ('SELL', 'Sell / Bearish 📉'), ('STRONG_SELL', 'Strong Sell ⚠️')], default='NEUTRAL', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Prediction confidence (0.0 to 100.0%)')),
                ('current_price_at_prediction', models.DecimalField(decimal_places=4, max_digits=14)),
                ('expected_target_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('upper_corridor_band', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lower_corridor_band', models.DecimalField(decimal_places=4, max_digits=14)),
                ('suggested_entry', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=14)),
                ('take_profit_1', models.DecimalField(decimal_places=4, max_digits=14)),
                ('take_profit_2', models.DecimalField(decimal_places=4, max_digits=14)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('technical_score', models.FloatField(default=0.0)),
                ('macro_score', models.FloatField(default=0.0)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('summary_analysis', models.TextField(blank=True, null=True)),
                ('target_date', models.DateTimeField(db_index=True)),
                ('actual_price_at_target', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('was_accurate', models.BooleanField(blank=True, help_text='True if directional movement was correctly hit', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='market_data.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
