# Generated by Django 6.1.1 on 2026-09-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='horizon_label',
            field=models.CharField(default='7-Day Swing', help_text='Human-readable horizon', max_length=50),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='tp1_target_date',
            field=models.DateField(blank=True, help_text='Expected Date to hit Take-Profit 1', null=True),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='tp2_target_date',
            field=models.DateField(blank=True, help_text='Expected Date to hit Take-Profit 2', null=True),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='timeframe',
            field=models.CharField(choices=[('15m', '15 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], default='1d', max_length=5),
        ),
    ]
